---
- name: Deploy backhaul Docker container
  hosts: all
  become: true # Run with elevated privileges if needed for Docker

  vars:
    backhaul_transport: tcp
    backhaul_mode: server

  tasks:
    - name: Pull the backhaul_tunnel image
      community.docker.docker_image:
        name: ghcr.io/mahdishariatzade/backhaul_tunnel:latest
        source: pull
      tags: pull_image

    - name: Ensure directory for backhaul
      file:
        path: /srv/backhaul
        state: directory
        mode: '0755'
      tags: ensure_directory

    - name: Render config.toml from template
      template:
        src: templates/{{ backhaul_transport }}_{{ backhaul_mode }}.j2
        dest: /srv/backhaul/config.toml
      tags: render_config

    - name: Install OpenSSL if not present
      become: true
      ansible.builtin.package:
        name: openssl
        state: present
      tags: install_openssl

    - name: Generate self-signed SSL certificate
      shell: |
        openssl genpkey -algorithm RSA -out /srv/backhaul/server.key -pkeyopt rsa_keygen_bits:2048
        openssl req -new -key /srv/backhaul/server.key -out /srv/backhaul/server.csr -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN={{ ansible_host | default('localhost') }}/emailAddress=blckht.49@gmail.com"
        openssl x509 -req -in /srv/backhaul/server.csr -signkey /srv/backhaul/server.key -out /srv/backhaul/server.crt -days 365
        rm /srv/backhaul/server.csr  # Clean up CSR file
      args:
        creates: /srv/backhaul/server.crt
      when: backhaul_mode == 'server' and backhaul_transport in ['wss', 'wssmux']
      tags: generate_ssl

    - name: Run the backhaul container
      community.docker.docker_container:
        name: backhaul
        image: ghcr.io/mahdishariatzade/backhaul_tunnel:latest
        state: started
        restart_policy: unless-stopped
        network_mode: host
        env:
          BACKHAUL_CONFIG: 'config.toml'
        sysctls:
          net.ipv4.ip_local_port_range: '1024 65535'
          net.ipv4.tcp_tw_reuse: '1'
          net.ipv4.tcp_fin_timeout: '15'
          net.core.somaxconn: '4096'
          net.ipv4.tcp_max_syn_backlog: '8192'
          net.ipv4.tcp_window_scaling: '1'
          net.ipv4.tcp_fastopen: '3'
          net.ipv4.tcp_rmem: '16384 262144 1048576'
          net.ipv4.tcp_wmem: '16384 262144 1048576'
          net.ipv4.tcp_notsent_lowat: '4096'
          net.core.rmem_default: '262144'
          net.core.wmem_default: '262144'
          net.core.wmem_max: '67108864'
          net.core.rmem_max: '67108864'
        volumes:
          - /srv/backhaul/config.toml:/app/config.toml:ro
          - /srv/backhaul/server.crt:/root/server.crt:ro
          - /srv/backhaul/server.key:/root/server.key:ro
      when: backhaul_mode == 'server' and backhaul_transport in ['wss', 'wssmux']
      tags: run_container_ssl

    - name: Run the backhaul container (without certs)
      community.docker.docker_container:
        name: backhaul
        image: ghcr.io/mahdishariatzade/backhaul_tunnel:latest
        state: started
        restart_policy: unless-stopped
        network_mode: host
        env:
          BACKHAUL_CONFIG: 'config.toml'
        sysctls:
          net.ipv4.ip_local_port_range: '1024 65535'
          net.ipv4.tcp_tw_reuse: '1'
          net.ipv4.tcp_fin_timeout: '15'
          net.core.somaxconn: '4096'
          net.ipv4.tcp_max_syn_backlog: '8192'
          net.ipv4.tcp_window_scaling: '1'
          net.ipv4.tcp_fastopen: '3'
          net.ipv4.tcp_rmem: '16384 262144 1048576'
          net.ipv4.tcp_wmem: '16384 262144 1048576'
          net.ipv4.tcp_notsent_lowat: '4096'
          net.core.rmem_default: '262144'
          net.core.wmem_default: '262144'
          net.core.wmem_max: '67108864'
          net.core.rmem_max: '67108864'
        volumes:
          - /srv/backhaul/config.toml:/app/config.toml:ro
      when: not (backhaul_mode == 'server' and backhaul_transport in ['wss', 'wssmux'])
      tags: run_container
