---
- name: APT Update and Upgrade
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vars.yml

  tasks:
    - name: APT maintenance on APT-based systems
      block:
        - name: Force unlock APT if stale locks detected (optional)
          block:
            - name: Stop apt-daily timers to avoid races
              ansible.builtin.systemd:
                name: '{{ item }}'
                state: stopped
                enabled: false
              loop:
                - apt-daily.timer
                - apt-daily-upgrade.timer
              failed_when: false
              when: force_unlock_apt | default(false)

            - name: Stop apt services if running
              ansible.builtin.systemd:
                name: '{{ item }}'
                state: stopped
              loop:
                - apt-daily.service
                - apt-daily-upgrade.service
              failed_when: false
              when: force_unlock_apt | default(false)

            - name: Kill stale apt/dpkg processes
              ansible.builtin.shell: |
                set -Eeuo pipefail
                pkill -9 -x apt || true
                pkill -9 -x apt-get || true
                pkill -9 -x aptitude || true
                pkill -9 -x dpkg || true
                pkill -9 -f unattended-upgrade || true
                pkill -9 -f apt.systemd.daily || true
              args:
                executable: /bin/bash
              changed_when: true
              failed_when: false
              when: force_unlock_apt | default(false)

            - name: Remove APT lock files
              ansible.builtin.file:
                path: '{{ item }}'
                state: absent
              loop:
                - /var/lib/apt/lists/lock
                - /var/lib/dpkg/lock
                - /var/lib/dpkg/lock-frontend
                - /var/cache/apt/archives/lock
              when: force_unlock_apt | default(false)

            - name: Reconfigure dpkg database
              ansible.builtin.shell: |
                set -e
                dpkg --configure -a
              args:
                executable: /bin/bash
              changed_when: false
              failed_when: false
              when: force_unlock_apt | default(false)

          when: force_unlock_apt | default(false)

        - name: Prevent service restarts during upgrade (policy-rc.d)
          ansible.builtin.copy:
            dest: /usr/sbin/policy-rc.d
            mode: '0755'
            content: |
              #!/bin/sh
              exit 101
          when: prevent_service_restarts | default(true)

        - name: Fix dpkg half-configured packages
          ansible.builtin.command:
            cmd: dpkg --configure -a
          changed_when: false
          when: run_dpkg_configure | default(true)

        - name: Attempt to fix broken dependencies (optional)
          ansible.builtin.command:
            cmd: >-
              apt-get -y -o Dpkg::Options::=--force-confdef
              -o Dpkg::Options::=--force-confold -f install
          changed_when: false
          environment:
            DEBIAN_FRONTEND: noninteractive
          when: apt_fix_broken_before_upgrade | default(false)

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true
            lock_timeout: '{{ apt_lock_timeout | default(600) }}'
          environment:
            DEBIAN_FRONTEND: noninteractive
            NEEDRESTART_MODE: 'l'

        - name: Upgrade installed packages
          ansible.builtin.apt:
            upgrade: "{{ apt_upgrade_type }}"
            lock_timeout: '{{ apt_lock_timeout | default(600) }}'
          environment:
            DEBIAN_FRONTEND: noninteractive
            NEEDRESTART_MODE: 'l'
      rescue:
        - name: Ensure policy-rc.d removed after failure
          ansible.builtin.file:
            path: /usr/sbin/policy-rc.d
            state: absent
          when: prevent_service_restarts | default(true)
        - name: Fail with error after cleanup
          ansible.builtin.fail:
            msg: 'APT maintenance failed; policy-rc.d removed'
      always:
        - name: Re-enable apt-daily timers if they were disabled
          ansible.builtin.systemd:
            name: '{{ item }}'
            enabled: true
            state: started
          loop:
            - apt-daily.timer
            - apt-daily-upgrade.timer
          when: force_unlock_apt | default(false)

        - name: Remove policy-rc.d to restore normal behavior
          ansible.builtin.file:
            path: /usr/sbin/policy-rc.d
            state: absent
          when: prevent_service_restarts | default(true)
      when: ansible_pkg_mgr == 'apt'
      tags:
        - apt
        - update
        - upgrade


