---
- name: Deploy Grafana Alloy Container
  hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Create directory for Alloy
      file:
        path: /opt/alloy
        state: directory
        mode: '0755'

    - name: Template Alloy config
      template:
        src: config.alloy.j2
        dest: /opt/alloy/conf.alloy
        force: '{{ replace_config | default(false) }}'
        mode: '0644'
      register: alloy_config_changed

    - name: Ensure inotify limits are sufficient on host
      when: ansible_os_family == 'Debian' and (edit_sysctl | default(false))
      sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: present
        reload: yes
      loop:
        - {
            name: 'fs.inotify.max_user_instances',
            value: '{{ inotify_max_user_instances | default(1024) }}',
          }
        - {
            name: 'fs.inotify.max_user_watches',
            value: '{{ inotify_max_user_watches | default(524288) }}',
          }
        - {
            name: 'fs.inotify.max_queued_events',
            value: '{{ inotify_max_queued_events | default(65536) }}',
          }

    - name: Run Alloy Docker container
      community.docker.docker_container:
        name: "{{ container_name | default('alloy') }}"
        image: grafana/alloy:latest
        state: started
        restart: '{{ alloy_config_changed.changed or force_restart | default(false) }}'
        restart_policy: unless-stopped
        env:
          GOMEMLIMIT: "{{ gomemlimit | default('2GiB') }}"
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:ro
          - /var/run/docker.sock:/var/run/docker.sock
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro

          - /opt/alloy/conf.alloy:/etc/alloy/config.alloy:ro

          - /etc/hostname:/etc/hostname:ro

          - /proc:/host/proc:ro
          - /run/udev/data:/run/udev/data:ro
        ports:
          - '127.0.0.1:12345:12345' # for debug
        command:
          - run
          - --server.http.listen-addr=0.0.0.0:12345
          - --storage.path=/var/lib/alloy/data
          - /etc/alloy/config.alloy
        capabilities:
          - SYS_TIME
        uts: host
        cpu_shares: 512 # Approximate for 0.5 CPUs
        memory: 2G
        # Raise open-file limit inside the container so Alloy can create enough
        # inotify descriptors. These values are conservative but well above
        # the defaults (soft/hard = 1024/4096).
        ulimits:
          - 'nofile:65536:65536'
