---
# tasks file for discover_containers
# roles/discover_containers/tasks/main.yml
- name: List all Docker containers as JSON
  shell: docker ps -a --format 'json'
  register: containers_raw

- name: Initialize containers_with_labels
  set_fact:
    containers_with_labels: []

- name: Build list of container names and labels
  set_fact:
    containers_with_labels: "{{ containers_with_labels + [ {'name': item.Names, 'labels': (item.Labels | default('') | split(',')) } ] }}"
  loop: "{{ containers_raw.stdout_lines | map('from_json') | list }}"
  loop_control:
    label: '{{ item.Names }}'

- name: Set filtered_containers to all containers by default
  set_fact:
    filtered_containers: '{{ containers_with_labels }}'

- name: Create name regex pattern
  set_fact:
    name_regex: "{{ name_filter if (name_filter is string) else (name_filter | join('|')) }}"
  when: name_filter is defined and name_filter | length > 0

- name: Filter containers by name_filter if provided
  set_fact:
    filtered_containers: "{{ filtered_containers | selectattr('name', 'search', name_regex) | list }}"
  when: name_filter is defined and name_filter | length > 0

- name: Create effective label list
  set_fact:
    effective_labels: '{{ label_filter if (label_filter is iterable and not label_filter is string) else [label_filter] }}'
  when: label_filter is defined and label_filter | length > 0

- name: Initialize temp_filtered for labels
  set_fact:
    temp_filtered: []
  when: label_filter is defined and label_filter | length > 0

- name: Filter containers by label_filter if provided
  set_fact:
    temp_filtered: '{{ temp_filtered + [item] }}'
  loop: '{{ filtered_containers }}'
  when:
    - label_filter is defined and label_filter | length > 0
    - item.labels | intersect(effective_labels) | length > 0

- name: Update filtered_containers with label filter results
  set_fact:
    filtered_containers: '{{ temp_filtered }}'
  when: label_filter is defined and label_filter | length > 0
